"""Initial schema

Revision ID: 119668e4a9de
Revises: 
Create Date: 2026-05-21 01:20:39.692066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '119668e4a9de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tmdb_api_key', sa.String(length=256), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('MOVIE', 'TV_SHOW', 'CARTOON', 'ANIME', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('my_rating', sa.SmallInteger(), nullable=True),
    sa.Column('my_comments', sa.Text(), nullable=True),
    sa.Column('watch_status', sa.Enum('PLAN_TO_WATCH', 'WATCHING', 'COMPLETED', 'FAVORITE', 'DROPPED', name='watchstatus'), nullable=False),
    sa.Column('is_rewatch', sa.Boolean(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=2048), nullable=True),
    sa.Column('local_cover_url', sa.String(length=2048), nullable=True),
    sa.Column('web_url', sa.String(length=2048), nullable=True),
    sa.Column('local_network_url', sa.String(length=2048), nullable=True),
    sa.Column('api_audio_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('api_subtitle_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('local_audio_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('local_subtitle_languages', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('global_rating', sa.Float(), nullable=True),
    sa.Column('release_year', sa.SmallInteger(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('my_rating IS NULL OR (my_rating >= 1 AND my_rating <= 10)', name='ck_media_rating_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_index(op.f('ix_media_title'), 'media', ['title'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media_genres',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.create_table('media_tags',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'tag_id')
    )
    op.create_table('screenshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('season_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'season_number', name='uq_season_media_number')
    )
    op.create_table('episodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('episode_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('is_watched', sa.Boolean(), nullable=False),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season_id', 'episode_number', name='uq_episode_season_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episodes')
    op.drop_table('seasons')
    op.drop_table('screenshots')
    op.drop_table('media_tags')
    op.drop_table('media_genres')
    op.drop_table('tags')
    op.drop_index(op.f('ix_media_title'), table_name='media')
    op.drop_table('media')
    op.drop_table('genres')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
